apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-service
  namespace: {{ .Chart.Name}}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
