apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}
  namespace: {{ .Values.todoapp.namespace}}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007
